require('dino.plugins')
require('dino.lsp.zero-lsp')
require('dino.lsp.null-ls')
require('dino.options')
require('dino.keymaps')
require('dino.colors')
require('dino.telescope')
require('dino.nvim-tree')
require('dino.treesitter')
require('dino.bufferline')
require('dino.whichkey')
require('dino.lualine')

