#!/bin/bash

options=(
	style=round
	width=8.0
	hidpi=off
	active_color=0xff9ccfd8     # rose (accent for active border)
	inactive_color=0xff6e6a86   # overlay (for inactive border)
)

borders "${options[@]}"
