require('dino.plugins')
require('dino.options')
require('dino.keymaps')
require('dino.colors')
require('dino.comments')
require('dino.telescope')
require('dino.nvim-tree')
-- require('dino.lsp.cmp')
require('dino.treesitter')
-- require('dino.mason')
-- require('dino.lsp')
require('dino.lsp.zero')
require('dino.lsp.null-ls')
require('dino.bufferline')
require('dino.whichkey')
require('dino.harpoon')
-- require('dino.lualine')
-- require('dino.project')
