
require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.lsp')
require('user.lsp.null-ls')
require('user.tree-sitter')
require('user.nvim-tree')
require('user.telescope')
require('user.whichkey')
require('user.cmp')
require('user.auto-cmd')
require('user.lualine')
require('user.bufferline')
require('user.toggle-term')
require('user.autopairs')

