require('dino.lsp.null-ls')
require('dino.plugins')
require('dino.options')
require('dino.keymaps')
require('dino.colors')
require('dino.comments')
require('dino.telescope')
require('dino.nvim-tree')
require('dino.treesitter')
require('dino.bufferline')
require('dino.whichkey')
require('dino.lualine')
require('dino.lsp.zero-lsp-2')

-- old LSP
-- require('dino.mason')
-- require('dino.lsp')
-- require('dino.lsp.null-ls')
-- require('dino.cmp')

